# Sass-lint
#
# Configuration
options:
  # Don't merge default rules
  merge-default-rules: false
  formatter: stylish
  # Raise an error if more than 10 warnings are generated
  max-warnings: 10

# Rules
rules:
  attribute-quotes: true
  bem-depth:
    - 1
    -
      max-depth: 2
  border-zero:
    - 1
    -
      convention: '0'
  brace-style:
    - 1
    -
      style: '1tbs'
      allow-single-line: false
  class-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: 'hyphenatedbem'
  clean-import-paths:
    - 1
    -
      leading-underscore: true
      filename-extension: true
  declarations-before-nesting: true
  empty-args:
    - 1
    -
      include: false
  empty-line-between-blocks:
    - 0
    -
      allow-single-line-rulesets: false
  extends-before-declarations: true
  extends-before-mixins: true
  final-newline: true
  force-attribute-nesting: false
  force-element-nesting: true
  force-pseudo-nesting: true
  function-name-format:
    - 1
    -
      allow-leading-underscore: true
      convention: 'hypenatedlowercase'
  hex-length: long
  hex-notation: 'lowercase'
  id-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  indentation:
    - 2
    -
      size: 2
  leading-zero:
    - 1
    -
      include: false
  mixin-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  mixins-before-declarations: true
  nesting-depth: 3
  no-attribute-selectors: false
  no-color-hex: false
  no-color-keywords: true
  no-color-literals: true
  no-combinators: 0
  no-css-comments: true
  no-debug: true
  no-disallowed-properties: false
  no-duplicate-properties: false
  no-empty-rulesets: true
  no-extends: true
  no-ids: false
  no-important: true
  no-invalid-hex: true
  no-mergeable-selectors: false
  no-misspelled-properties: true
  # Using BEM, this really shouldn't happen
  no-qualifying-elements: true
  #
  no-trailing-whitespace: true
  no-trailing-zero: true
  no-transition-all: true
  no-universal-selectors: 0
  no-url-domains: true
  no-url-protocols: true
  no-vendor-prefixes: 0
  no-warn: false
  one-declaration-per-line: true
  placeholder-in-extend: false
  placeholder-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  quotes:
    - 1
    -
      style: 'single'
  shorthand-values: 1
  single-line-per-selector: true
  space-after-bang:
    - 1
    -
      include: false
  space-after-colon:
    - 1
    -
      include: true
  space-after-comma:
    - 1
    -
      include: true
  space-around-operator:
    - 1
    -
      include: true
  space-before-bang:
    - 1
    -
      include: true
  space-before-brace:
    - 1
    -
      include: true
  space-before-colon:
    - 1
    -
      include: false
  space-between-parens:
    - 1
    -
      include: false
  trailing-semicolon:
    - 1
    -
      include: true
  url-quotes: true
  variable-for-property: true
  variable-name-format:
    - 1
    -
      allow-leading-underscore: true
      convention: 'hyphenatedlowercase'
  zero-unit:
    - 1
    -
      include: false
